<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Mapnik-users] Quantumnik error
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/mapnik-users/2011-February/index.html" >
   <LINK REL="made" HREF="mailto:mapnik-users%40lists.berlios.de?Subject=Re%3A%20%5BMapnik-users%5D%20Quantumnik%20error&In-Reply-To=%3C4D5ACF82.4020406%40peterse-uithuizen.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="004059.html">
   <LINK REL="Next"  HREF="004012.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mapnik-users] Quantumnik error</H1>
    <B>Peter Peterse</B> 
    <A HREF="mailto:mapnik-users%40lists.berlios.de?Subject=Re%3A%20%5BMapnik-users%5D%20Quantumnik%20error&In-Reply-To=%3C4D5ACF82.4020406%40peterse-uithuizen.com%3E"
       TITLE="[Mapnik-users] Quantumnik error">peter at peterse-uithuizen.com
       </A><BR>
    <I>Tue Feb 15 20:09:54 CET 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="004059.html">[Mapnik-users] PHP mapnik
</A></li>
        <LI>Next message: <A HREF="004012.html">[Mapnik-users] Quantumnik error
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#4011">[ date ]</a>
              <a href="thread.html#4011">[ thread ]</a>
              <a href="subject.html#4011">[ subject ]</a>
              <a href="author.html#4011">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hello,

I've a problem with QGIS and Quantumnik. When I start Quantumnik I get
an error:
==============

Traceback (most recent call last):
  File &quot;C:/Users/myname/.qgis/python/plugins\quantumnik\quantumnik.py&quot;, line 199, in toggle
    self.start_rendering()
  File &quot;C:/Users/myname/.qgis/python/plugins\quantumnik\quantumnik.py&quot;, line 415, in start_rendering
    self.create_mapnik_map()
  File &quot;C:/Users/myname/.qgis/python/plugins\quantumnik\quantumnik.py&quot;, line 382, in create_mapnik_map
    self.mapnik_map = self.easyCanvas.to_mapnik()
  File &quot;C:/Users/myname/.qgis/python/plugins\quantumnik\sync.py&quot;, line 1256, in to_mapnik
    if lyr_a.is_valid():
  File &quot;C:/Users/myname/.qgis/python/plugins\quantumnik\sync.py&quot;, line 1091, in is_valid
    ds = self.datasource()
  File &quot;C:/Users/myname/.qgis/python/plugins\quantumnik\sync.py&quot;, line 762, in datasource
    return self.ogr()
  File &quot;C:/Users/myname/.qgis/python/plugins\quantumnik\sync.py&quot;, line 60, in newf
    return f(*_args, **_kwds)
  File &quot;C:/Users/myname/.qgis/python/plugins\quantumnik\sync.py&quot;, line 894, in ogr
    return mapnik.Ogr(file=self.source,layer=self.sub_layer_name,multiple_geometries=multiple_geometries)
  File &quot;D:\OSGeo4W\apps\Python25\lib\site-packages\mapnik\__init__.py&quot;, line 418, in Ogr
    return CreateDatasource(keywords)
RuntimeError: Connection failed: PG:dbname='top10nl' host='remote-localhost' port='5432' user='dbuser' password='pwd231s' was not found or is not a supported format

Python versie:
2.5.2 (r252:60911, Feb 21 2008, 13:11:45) [MSC v.1310 32 bit (Intel)]


QGIS versie:
1.6.0-Capiapo Capiapo, exported

Python pad: ['D:/OSGeo4W/apps/qgis/./python', 'C:/Users/myname/.qgis/python', 'C:/Users/myname/.qgis/python/plugins', 'D:/OSGeo4W/apps/qgis/./python/plugins', 'D:\\OSGeo4W\\apps\\gdal-17\\pymod', 'C:\\', 'D:\\OSGeo4W\\bin\\python25.zip', 'D:\\OSGeo4W\\apps\\Python25\\DLLs', 'D:\\OSGeo4W\\apps\\Python25\\lib', 'D:\\OSGeo4W\\apps\\Python25\\lib\\plat-win', 'D:\\OSGeo4W\\apps\\Python25\\lib\\lib-tk', 'D:\\OSGeo4W\\apps\\qgis\\bin', 'D:\\OSGeo4W\\apps\\Python25', 'D:\\OSGeo4W\\apps\\Python25\\lib\\site-packages', 'D:\\OSGeo4W\\apps\\qgis\\python\\plugins\\fTools\\tools']

==============

QGIS has no problem to create a databse connection. It shows the map
without any problems.

Can anyone help me to solve this problem?

Thanks,
Peter
-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;<A HREF="https://lists.berlios.de/pipermail/mapnik-users/attachments/20110215/e1437b62/attachment.html">https://lists.berlios.de/pipermail/mapnik-users/attachments/20110215/e1437b62/attachment.html</A>&gt;
</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="004059.html">[Mapnik-users] PHP mapnik
</A></li>
	<LI>Next message: <A HREF="004012.html">[Mapnik-users] Quantumnik error
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#4011">[ date ]</a>
              <a href="thread.html#4011">[ thread ]</a>
              <a href="subject.html#4011">[ subject ]</a>
              <a href="author.html#4011">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/mapnik-users">More information about the Mapnik-users
mailing list</a><br>
</body></html>
