<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Mapnik-users] Mapnik Runtime Error
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/mapnik-users/2008-August/index.html" >
   <LINK REL="made" HREF="mailto:mapnik-users%40lists.berlios.de?Subject=Re%3A%20%5BMapnik-users%5D%20Mapnik%20Runtime%20Error&In-Reply-To=%3C48979A10.2050802%40bikelab.org%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="001049.html">
   <LINK REL="Next"  HREF="001051.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mapnik-users] Mapnik Runtime Error</H1>
    <B>Jens Herrmann</B> 
    <A HREF="mailto:mapnik-users%40lists.berlios.de?Subject=Re%3A%20%5BMapnik-users%5D%20Mapnik%20Runtime%20Error&In-Reply-To=%3C48979A10.2050802%40bikelab.org%3E"
       TITLE="[Mapnik-users] Mapnik Runtime Error">mapnik at bikelab.org
       </A><BR>
    <I>Tue Aug  5 02:08:48 CEST 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="001049.html">[Mapnik-users] Building Mapnik on Solaris
</A></li>
        <LI>Next message: <A HREF="001051.html">[Mapnik-users] Mapnik Runtime Error
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1050">[ date ]</a>
              <a href="thread.html#1050">[ thread ]</a>
              <a href="subject.html#1050">[ subject ]</a>
              <a href="author.html#1050">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hello,
I have got a got problem with a runtime error when using 
generate_image.py. The full error message is:

###########################
got exception ...
Traceback (most recent call last):
   File &quot;./generate_image.py&quot;, line 37, in &lt;module&gt;
     load_map(m,mapfile)
RuntimeError: failed opening file: Bad file descriptor
###########################

This happens with python-mapnik 0.4.0-2 (Ubuntu Hardy) as well as with 
0.5.1-2 (Ubuntu Intrepid). Everything worked just fine to this point (no 
warnings etc). I have found nothing in the list archive and only one 
thread with Google where this problem is addressed, unfortunately in 
French which I do not understand. 
(<A HREF="http://www.mail-archive.com/talk-fr@openstreetmap.org/msg02434.html">http://www.mail-archive.com/talk-fr@openstreetmap.org/msg02434.html</A>)
Can anyone help?

Thanks
Jens

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="001049.html">[Mapnik-users] Building Mapnik on Solaris
</A></li>
	<LI>Next message: <A HREF="001051.html">[Mapnik-users] Mapnik Runtime Error
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1050">[ date ]</a>
              <a href="thread.html#1050">[ thread ]</a>
              <a href="subject.html#1050">[ subject ]</a>
              <a href="author.html#1050">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/mapnik-users">More information about the Mapnik-users
mailing list</a><br>
</body></html>
