<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Mapnik-users] Mapnik Runtime Error
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/mapnik-users/2008-August/index.html" >
   <LINK REL="made" HREF="mailto:mapnik-users%40lists.berlios.de?Subject=Re%3A%20%5BMapnik-users%5D%20Mapnik%20Runtime%20Error&In-Reply-To=%3C1217896716.3754.187.camel%40localhost.localdomain%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="001050.html">
   <LINK REL="Next"  HREF="001052.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mapnik-users] Mapnik Runtime Error</H1>
    <B>Jon Burgess</B> 
    <A HREF="mailto:mapnik-users%40lists.berlios.de?Subject=Re%3A%20%5BMapnik-users%5D%20Mapnik%20Runtime%20Error&In-Reply-To=%3C1217896716.3754.187.camel%40localhost.localdomain%3E"
       TITLE="[Mapnik-users] Mapnik Runtime Error">jburgess777 at googlemail.com
       </A><BR>
    <I>Tue Aug  5 02:38:36 CEST 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="001050.html">[Mapnik-users] Mapnik Runtime Error
</A></li>
        <LI>Next message: <A HREF="001052.html">[Mapnik-users] SLD
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1051">[ date ]</a>
              <a href="thread.html#1051">[ thread ]</a>
              <a href="subject.html#1051">[ subject ]</a>
              <a href="author.html#1051">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Tue, 2008-08-05 at 02:08 +0200, Jens Herrmann wrote:
&gt;<i> Hello,
</I>&gt;<i> I have got a got problem with a runtime error when using 
</I>&gt;<i> generate_image.py. The full error message is:
</I>&gt;<i> 
</I>&gt;<i> ###########################
</I>&gt;<i> got exception ...
</I>&gt;<i> Traceback (most recent call last):
</I>&gt;<i>    File &quot;./generate_image.py&quot;, line 37, in &lt;module&gt;
</I>&gt;<i>      load_map(m,mapfile)
</I>&gt;<i> RuntimeError: failed opening file: Bad file descriptor
</I>&gt;<i> ###########################
</I>&gt;<i> 
</I>&gt;<i> This happens with python-mapnik 0.4.0-2 (Ubuntu Hardy) as well as with 
</I>&gt;<i> 0.5.1-2 (Ubuntu Intrepid). Everything worked just fine to this point (no 
</I>&gt;<i> warnings etc). I have found nothing in the list archive and only one 
</I>&gt;<i> thread with Google where this problem is addressed, unfortunately in 
</I>&gt;<i> French which I do not understand. 
</I>&gt;<i> (<A HREF="http://www.mail-archive.com/talk-fr@openstreetmap.org/msg02434.html">http://www.mail-archive.com/talk-fr@openstreetmap.org/msg02434.html</A>)
</I>&gt;<i> Can anyone help?
</I>
I think the last time someone had this issue it turned out that the
shapefiles were missing because he had not downloaded the coastline
data.

	Jon



</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="001050.html">[Mapnik-users] Mapnik Runtime Error
</A></li>
	<LI>Next message: <A HREF="001052.html">[Mapnik-users] SLD
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1051">[ date ]</a>
              <a href="thread.html#1051">[ thread ]</a>
              <a href="subject.html#1051">[ subject ]</a>
              <a href="author.html#1051">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/mapnik-users">More information about the Mapnik-users
mailing list</a><br>
</body></html>
