<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Mapnik-users]  ImportError undefined symbol Py_Init_Module
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/mapnik-users/2011-July/index.html" >
   <LINK REL="made" HREF="mailto:mapnik-users%40lists.berlios.de?Subject=Re%3A%20%5BMapnik-users%5D%20%20ImportError%20undefined%20symbol%20Py_Init_Module&In-Reply-To=%3C32008257.post%40talk.nabble.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="004382.html">
   <LINK REL="Next"  HREF="004388.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mapnik-users]  ImportError undefined symbol Py_Init_Module</H1>
    <B>Sean Silbaugh</B> 
    <A HREF="mailto:mapnik-users%40lists.berlios.de?Subject=Re%3A%20%5BMapnik-users%5D%20%20ImportError%20undefined%20symbol%20Py_Init_Module&In-Reply-To=%3C32008257.post%40talk.nabble.com%3E"
       TITLE="[Mapnik-users]  ImportError undefined symbol Py_Init_Module">Ssilbaugh at 42six.com
       </A><BR>
    <I>Wed Jul  6 22:38:57 CEST 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="004382.html">[Mapnik-users] Plant database update
</A></li>
        <LI>Next message: <A HREF="004388.html">[Mapnik-users] ImportError undefined symbol Py_Init_Module
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#4387">[ date ]</a>
              <a href="thread.html#4387">[ thread ]</a>
              <a href="subject.html#4387">[ subject ]</a>
              <a href="author.html#4387">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
Hello,

I am trying to get Mapnik to render maps for a WMS server I am trying to
host.  However, whenever I run  generate_image.py, it gives me an error
saying &quot;ImportError: /usr/local/lib/libboost_python.so.1.43.0:undefined
symbol: Py_Init_Module4_64&quot;.  I have boost version 1.43 as well as python v
2.6 installed.  I am on Centos 5 and I had no problems installing mapnik. 
The only problem I have is when I try to run generate_image.py.  I have
tried to export LD_LIBRARY_CONFIG=/usr/local/lib64 as well as
/usr/local/lib64.  Any help would be greatly appreciated.

Thanks!
Sean
-- 
View this message in context: <A HREF="http://old.nabble.com/ImportError-undefined-symbol-Py_Init_Module-tp32008257p32008257.html">http://old.nabble.com/ImportError-undefined-symbol-Py_Init_Module-tp32008257p32008257.html</A>
Sent from the Mapnik - Users mailing list archive at Nabble.com.


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="004382.html">[Mapnik-users] Plant database update
</A></li>
	<LI>Next message: <A HREF="004388.html">[Mapnik-users] ImportError undefined symbol Py_Init_Module
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#4387">[ date ]</a>
              <a href="thread.html#4387">[ thread ]</a>
              <a href="subject.html#4387">[ subject ]</a>
              <a href="author.html#4387">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/mapnik-users">More information about the Mapnik-users
mailing list</a><br>
</body></html>
